import Head from "next/head";
import { ReactNode } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
type IType = {
  children: ReactNode;
};

export default function Index({ children }: IType) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />
    </div>
  );
}
